-   id: pyrefly
    name: pyrefly
    description: 'pyrefly type checking'
    entry: pyrefly check
    language: python
    'types_or': [python, pyi]
    args: []
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: '2.9.2'